name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request: {}
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.platform }} (${{ matrix.python-version }})
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        platform: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[testing]"

      - name: Install Micro-Manager
        run: python -m pymmcore_plus.install

      - name: Test
        run: pytest -v --color=yes --cov=pycro_plus_bridge --cov-report=xml

      - name: Coverage
        uses: codecov/codecov-action@v2
